wandb_version: 1

iterations:
  desc: null
  value: 1383
od_wait:
  desc: null
  value: 40
learning_rate:
  desc: null
  value: 0.048874458688324886
reg_lambda:
  desc: null
  value: 3.491598561612883
subsample:
  desc: null
  value: 0.8356954568350058
random_strength:
  desc: null
  value: 39.72019974335227
depth:
  desc: null
  value: 8
min_data_in_leaf:
  desc: null
  value: 1
leaf_estimation_iterations:
  desc: null
  value: 14
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.14.2
    framework: catboost
    huggingface_version: 4.28.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681963809.037154
    t:
      1:
      - 1
      - 5
      - 6
      - 7
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 7
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.14.2
      6: 4.28.0
      8:
      - 4
      - 5
